import { IsNotEmpty, IsObject, IsOptional, IsString, IsUUID } from 'class-validator';

/**
 * DTO for creating simulation feedback
 */
export class CreateSimulationFeedbackDto {
  /**
   * Session ID the feedback belongs to
   */
  @IsUUID()
  @IsNotEmpty()
  sessionId: string;

  /**
   * Feedback text generated by GPT
   */
  @IsString()
  @IsOptional()
  feedbackText?: string;

  /**
   * Checklist data in JSON format
   */
  @IsObject()
  @IsOptional()
  checklistJson?: Record<string, any>;
} 