import { IsObject, IsOptional, IsString } from 'class-validator';

/**
 * DTO for updating simulation feedback
 */
export class UpdateSimulationFeedbackDto {
  /**
   * Feedback text generated by GPT
   */
  @IsString()
  @IsOptional()
  feedbackText?: string;

  /**
   * Checklist data in JSON format
   */
  @IsObject()
  @IsOptional()
  checklistJson?: Record<string, any>;
} 